### ISSUE TITLE
Clarifying My Promotion Step: Addressing a Potential Misalignment in Pay Scale Transition

### ISSUE THREAD

**Issue by khalitko** [andrewnordlund/backpayCalc#101]
https://andrewnordlund.github.io/backpayCalc/2021/backpayCalc.html?lvl=1&stp=1&strtdt=2019-12-30&enddt=2024-02-14&pdate0=2023-12-11&plvl0=2&afrom0=2022-04-04&ato0=2022-08-04&alvl0=2&afrom1=2022-08-08&ato1=2022-12-08&alvl1=2&afrom2=2023-09-18&ato2=2023-12-11&alvl2=2

I've been looking over my pay and the steps for when I was acting and then got promoted to IT-02, and I think there's a mix-up with the steps they put me on. After I stopped acting and got my promotion, they were supposed to put me on a higher step so my pay wouldn't go down, but it looks like that didn't happen right. This mess-up means my backpay and what I'm getting paid now might not be what it's supposed to be. Can we check this out and fix it so it matches what the rules say I should be getting?

**Comment by khalitko** [comment]
And when I say they, I mean the calculator.

**Comment by andrewnordlund** [comment]
For the purposes of this calculator (and how pay increments work, as far as I'm aware) is that an acting that turns into a promotion, like what you have here, the promotion is considered to be the start of the acting.

In your case, you started acting IT-02 on Sept 8, 2023, and then, without returning to IT-01, that acting was made permanent on Dec 11, 2023.

So, now your IT-02 anniversary will be Sept 8.  This Sept. 8 (2024), you'll move up to the next IT-02 step.

This is what it should look like:  https://andrewnordlund.github.io/backpayCalc/2021/backpayCalc.html?lvl=1&stp=1&strtdt=2019-12-30&enddt=2024-02-14&pdate0=2023-09-08&plvl0=2&afrom0=2022-04-04&ato0=2022-08-04&alvl0=2&afrom1=2022-08-08&ato1=2022-12-08&alvl1=2

Now, that's taking you from IT-01 Step 4 to IT-02 Step 1.

@khalitko  Are you currently at IT-02 Step 1?  Or are you at Step 2?

I do know there's a slight bug in how promotion/acting pay is calculated.  I was hoping to work on that today if I can get the time.

**Comment by khalitko** [comment]
thanks for getting back to me, I'm currently an It-02 step 1, there's some weird adjustment to it though. Can I send you the excel sheet from my gc pay? I don't want to post it here 😅

**Comment by andrewnordlund** [comment]
Yeah, sure.  I'm not a payroll expert by any stretch.  So I'm kinda learning as I go here.

Are you able to find me through Outlook/Teams?

**Comment by khalitko** [comment]
I  think i see you on linkedin? https://www.linkedin.com/in/andrew-nordlund-52607734/?originalSubdomain=ca

**Comment by khalitko** [comment]
sent ya a follow

**Comment by andrewnordlund** [comment]
Yeah, that's me on LinkedIn.
