### ISSUE TITLE
Add Overtime at 1.0x rate

### ISSUE THREAD

**Issue by pducharme** [andrewnordlund/backpayCalc#15]
Hi, in case you do a lot of Stand-by, you get paid 1.0x of OT for each 8h periods of Stand-by without a call-back.  I accumulate a lot of those 1.0x since I was On-call 24-7 for 4 weeks during my vacation in 2019.

**Comment by andrewnordlund** [comment]
I was actually working on this when I saw this issue come in.

I figured I'd also throw in a stand-by thing as well.  (That's 0.25 time, right?  I hardly do any OT at all.)

And in doing so, I think I found another bug.  *sigh*

**Comment by pducharme** [comment]
It’s 1h per 8h period I think.  I’ll have to dig in to be sure.

**Comment by pducharme** [comment]
It’s actually :  1/2 hour per 4h period.

https://www.tbs-sct.gc.ca/agreements-conventions/view-visualiser-eng.aspx?id=1#toc12212212216 <https://www.tbs-sct.gc.ca/agreements-conventions/view-visualiser-eng.aspx?id=1#toc12212212216>

**Comment by andrewnordlund** [comment]
Okay, thanks for looking that up.

**Comment by andrewnordlund** [comment]
Okay, I think I fixed that issue, and added 1.0 OT and 0.125 (ie: stand-by).  Take a look, and if it's fixed, I'll close this.
