### ISSUE TITLE
Acting anniversary 

### ISSUE THREAD

**Issue by x-YAD-x** [andrewnordlund/backpayCalc#76]
It didnt calculate my acting anniversary right. I think it based it off of the date i started as 2or 3, but i think i am an edge case as my  anniversary dates were based off of previous acting dates. (Im acting it04 now (almost 2years...), and have had signifucabt actings in it 2 &3)

**Comment by rlambert27** [comment]
You'll need to add a few details, such as how to reproduce the issue, what you got as results and what were the expected results.

To Reproduce
(You can provide the URL of the calculator with your entries)

Actual Result
(What did you get as results)

Expected Result
(What were you expecting as results)

**Comment by rlambert27** [comment]
@x-YAD-x - Are you able to provide more details?

**Comment by rlambert27** [comment]
@x-YAD-x will close this today unless you are still having issues and can provide further details.
