### ISSUE TITLE
Acting for 1 year less

### ISSUE THREAD

**Issue by Korreia** [andrewnordlund/backpayCalc#78]
Hello, the tool does not provide any result when I had my acting into the tool.

Here the link to reproduce: https://andrewnordlund.github.io/backpayCalc/2021/backpayCalc.html?lvl=4&stp=6&strtdt=2019-11-01&enddt=2024-03-17&afrom0=2022-10-03&ato0=2023-10-02&alvl0=5

The result table is blank.

I've try other combinations and it seem that every time I put acting IT-05 the tool does not produce any result.

**Comment by andrewnordlund** [comment]
Uh oh!

I'll get to this as soon as I can.

Warning, though:  Sorry, but the calculator was built under the assumption we all got the same raises.  (I initially built it just for myself.). I never thought another level would get different raises than most.  But that's the case here.  IT-05s get an extra 1% in the first year.

**Comment by andrewnordlund** [comment]
Give it a try now.  Let me know how it goes and/or close this issue if you see it to be fixed.

**Comment by Korreia** [comment]
It works, thanks for your support :)
