### ISSUE TITLE
Acting 2 steps above level not working

### ISSUE THREAD

**Issue by SirLongo** [andrewnordlund/backpayCalc#79]
as an IT-02, it won't calculate acting as IT-04. now I know it's not common but there's a handful that I am aware of

**Comment by andrewnordlund** [comment]
I can't read your mind.  You'll need to add a few details, such as how to reproduce the issue, what you got as results and what were the expected results.

To Reproduce
(You can provide the URL of the calculator with your entries)

Actual Result
(What did you get as results)

Expected Result
(What were you expecting as results)

**Comment by SirLongo** [comment]
my apologies.  am an IT-02 and acted as an IT-04 and when I enter it, the calculate button doesn't do anything!

**Comment by rlambert27** [comment]
Still need more info, can you provide the dates you were acting? Also if you can post the URL after hitting calculate as it will contain your entries into the form. Since it's a super simple use case you may also want to provide which browser / OS combo you are using.

**Comment by rlambert27** [comment]
Here's an example where you were IT-02 when the contract started and you did an entire year (2022) as an acting IT-04. The table output can be seen at the following URL : https://andrewnordlund.github.io/backpayCalc/2021/backpayCalc.html?lvl=2&stp=1&strtdt=2020-01-01&enddt=2024-03-17&afrom0=2022-01-03&ato0=2022-12-30&alvl0=4

**Comment by SirLongo** [comment]
https://andrewnordlund.github.io/backpayCalc/2021/backpayCalc.html
