### ISSUE TITLE
Instructions question

### ISSUE THREAD

**Issue by rlambert27** [andrewnordlund/backpayCalc#82]
In the instructions portion of the calculator it indicates:

"_For example, let's say you became an IT-02 (step 1) on August 1, 2019. This tentative agreement would come into effect on December 22, 2021. No backpay will be calculated before the start date of the tentative agreement. So, from December 22, 2021 to July 31, 2022 your annual rate of pay will be $75 129. That's the first period. Then on August 1, 2022 you have your 1 year anniversary as an IT-02 and you move up to step 2. From August 1, 2022 to December 21, 2022 you'll have an annual rate of pay of $77 535. That's the second period_."

If you started as an IT-02 on August 1, 2019, then on August 1, 2022 you would be celebrating your 3 year anniversary and move up to step 3 no?

**Comment by andrewnordlund** [comment]
I fixed it in English.

Is it correct in French?
https://dev.nordburg.ca/calculators/backpayCalc/2021/arrDeSalCalc.html

**Comment by rlambert27** [comment]
Nope, I left it as until I could confirm with you. Will fix it tonight.
