### ISSUE TITLE
Acting levels limited to IT (excluding EX) 

### ISSUE THREAD

**Issue by Artologik-dot-ca** [andrewnordlund/backpayCalc#92]
It is possible to do acting EX duties, but the dropdown only shows IT level choices.  
Perhaps add another data element/choice based on a monetary amount (yearly,monthly,weekly,daily) ?

**Comment by rlambert27** [comment]
How would doing an acting EX stint have an impact on the calculation of your IT backpay calculation?

I think if you wanted a more accurate calculation you could add your EX acting times as an LWOP so that it doesn't affect the calculation.

**Comment by andrewnordlund** [comment]
Wow, I could have sworn I put that in there somewhere.  I guess not.

Yes, an acting as an EX would be the same as any acting outside the IT classification; it would be a leave-without-pay for the calculator purposes.

**Comment by rlambert27** [comment]
You know what @andrewnordlund I'm pretty sure I saw it somewhere also but I looked and couldn't find it. Perhaps it was a comment in another bug.

**Comment by andrewnordlund** [comment]
It's hinted at in the descriptive text for Promotions.

I should put that above.

![EX_LWoP](https://github.com/andrewnordlund/backpayCalc/assets/1805963/ad81dc69-432b-4c6c-aae5-73e8eda7b4f0)

**Comment by Artologik-dot-ca** [comment]
Thank you folks for the quick responses.  Did not  see the descriptive text above; my bad.
