### ISSUE TITLE
Inflation Comparitor

### ISSUE THREAD

**Issue by andrewnordlund** [andrewnordlund/backpayCalc#95]
Would it be possible to add something to indicate pay rates if they followed inflation?

**Comment by rlambert27** [comment]
I saw a post on Reddit which is similar to what you are indicating here:

https://www.reddit.com/r/CanadaPublicServants/comments/15361xa/updated_to_2022_analysis_of_public_service/

Perhaps it can give you ideas on how to do it for this solution.
